In [1]:
import numpy as np
import pandas as pd
T = 0.9285
A = 1119
WD = 0.30
WL = 0.25
WPP = 1.00 
Peso_piso = A * (WD + WL + WPP)
k = 0.75 + 0.50 * T
V = 4190.53

h_pisos = np.array([4, 7.6, 11.2, 14.8, 18.4, 22.0, 25.6, 29.2, 32.8, 36.4, 40.0, 43.6, 47.2])
h_pisos2 = np.array([4, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6, 3.6])
Pesos = np.ones([13])*Peso_piso

sum = np.sum(Pesos * (h_pisos ** k))
fx = []

for i in np.arange(0, 13, 1):
    fx.append(Pesos[i]*h_pisos[i]**k / sum * V)

fx = np.array(fx)
fx_col = fx * 0.25
fx_wall = fx * 0.75
fx_df = pd.DataFrame(fx, columns=['fuerzas laterales de piso (T)']) 
fx_col_df = pd.DataFrame(fx_col, columns=['fuerzas laterales de piso (T), para Columnas']) 
fx_wall_df = pd.DataFrame(fx_wall, columns=['fuerzas laterales de piso (T), para Muros']) 

VD = np.sum(fx)
print("La fuerza lateral total VD es: ", VD, "T")

Resul = pd.concat([fx_df, fx_col_df, fx_wall_df], axis=1)
Resul.head(len(h_pisos))

La fuerza lateral total VD es:  4190.53 T

,fuerzas laterales de piso (T),"fuerzas laterales de piso (T), para Columnas","fuerzas laterales de piso (T), para Muros"
0,32.576885,8.144221,24.432664
1,71.020892,17.755223,53.265669
2,113.728994,28.432249,85.296746
3,159.532255,39.883064,119.649191
4,207.808476,51.952119,155.856357
5,258.163568,64.540892,193.622676
6,310.322734,77.580684,232.742051
7,364.082113,91.020528,273.061584
8,419.283749,104.820937,314.462812
9,475.801241,118.950310,356.850931
10,533.530879,133.382720,400.148159
11,592.385862,148.096465,444.289396
12,652.292353,163.073088,489.219265

In [2]:
VD_wall = np.sum(fx_wall)
M_wall = fx_wall / 2 * h_pisos2
M_wall_df = pd.DataFrame(M_wall, columns=['Momentos en muros (T-m)'])
print(VD_wall)
M_total = np.sum(M_wall)
print("El momento total en muros es: ", M_total, "T-m")
M_wall_df.head(len(M_wall_df))

3142.8974999999996
El momento total en muros es:  5662.102032805652 T-m

    Momentos en muros (T-m)
0                 48.865328
1                 95.878204
2                153.534142
3                215.368544
4                280.541442
5                348.520817
6                418.935691
7                491.510852
8                566.033061
9                642.331675
10               720.266686
11               799.720913
12               880.594676